AWSTemplateFormatVersion: '2010-09-09'
Description: for new account

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SubnetId:
    Description: Name of en existing Subnet
    Type: AWS::EC2::Subnet::Id
    ConstraintDescription: must be the name of an existing Subnet
  InstanceType:
    Description: API EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    - m2.xlarge
    - m2.2xlarge
    - m2.4xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge

Resources:
  APIProd:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-922914f7
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      SecurityGroups:
        - !ImportValue SSHSecurityGroup

