AWSTemplateFormatVersion: '2010-09-09'
Description: for new account

Parameters:
  EnvironmentName:
    Description: Choose env name that you need to create
    Type: String
    Default: "ApiProduction"
    AllowedValues:
    - "ApiProduction"
    - "PortalProduction"
    - "ApiStage"
    - "PortalStage"
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 Key
    ConstraintDescription: must be the name of an existing Subnet
  VpcID:
    Description: Name of an existing VPC
    Type: AWS::EC2::VPC::Id
    ConstraintDescription: must be the name of an existing VPC
  InstancePort:
    Type: String
    Description: Listen Port
    Default: '80'
  InstanceType:
    Description: API EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    - m2.xlarge
    - m2.2xlarge
    - m2.4xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge

Resources:
  AIProdASG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enble SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 172.16.40.0/24
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 172.16.30.0/24
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 172.16.20.0/24
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 172.16.10.0/24
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
  APIProd:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-922914f7
      KeyName: !Ref KeyName
      Monitoring: false
      SecurityGroups:
        - !Ref AIProdASG
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName





