AWSTemplateFormatVersion: "2010-09-09"
Description: Create Security Group to allow access be ssh to the API Prod Env

Resources:
  AIProdASG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enble SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 172.16.40.0/24
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 172.16.30.0/24
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 172.16.20.0/24
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 172.16.10.0/24
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

Outputs:
  StackSSHApiProdSG:
    Description: The SSH Security Group for our Company
    Value: !Ref AIProdASG
    Export:
      Name: SSHSecurityGroup

