AWSTemplateFormatVersion: '2010-09-09'
Description: for new account
Mappings:
  RegionMap:
    us-east-1:
      AMI: "ami-14c5486b"
    us-east-2:
      AMI: "ami-922914f7"
    us-west-1:
      AMI: "ami-25110f45"
    us-west-2:
      AMI: "ami-e251209a"

Parameters:
  EnvType:
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues:
      - prod
      - test
      - qa
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  VPCName:
    Description: Name of an existing VPC
    Type: AWS::EC2::VPC::Id
    ConstraintDescription: must be the ID of an existing VPC
  SubnetName:
    Description: Name of an existing Subnet
    Type: AWS::EC2::Subnet::Id
    ConstraintDescription: must be the ID of an existing Subnet
  SGName:
    Description: Name of an existing Security Group
    Type: AWS::EC2::SecurityGroup::GroupName
    ConstraintDescription: must be the name of an existing SG
  InstanceType:
    Description: API EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    - m2.xlarge
    - m2.2xlarge
    - m2.4xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge

    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  APIProd:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      ImageId:
        Fn::FindInMap:
          - "RegionMap"
          - Ref: "AWS::Region"
          - "AMI
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetName
      SecurityGroups: !Ref SGName