AWSTemplateFormatVersion: "2010-09-09"
Description: Restoring AWS RDS for local development from latest prod shapshot

Parameters:
  DBInstanceType:
    Description: Choose an existing DB class
    Type: String
    Default: db.t2.micro
  DBUser:
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: must contain only alphanumeric characters.
  DBInstanceIdentifier:
    Description: name of RDS Instance
    Type: String
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: must contain only alphanumeric characters.
  StorageType:
    Description: Choose an existing storage type
    Type: String
    Default: 'gp2'
    AllowedValues:
    - 'gp2'
    - 'io1'
    - 'standart'
  PubclicAccess:
    Description: Allow access from outside AWS VPC
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
  AutoMinorVersionUpgrade:
    Description: Allow Automatic Minor Version Upgrades?
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
  MultiAZ:
    Description: Enable Multi Availability Zones
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
  DBSubnetGroupName:
    Description: SubnetGroupName
    Type: String
  SnapshotIdent:
    Description: The latest shapshot of prod DB
    Type: String
  VpcSG:
    Description: VPC SG
    Type: String

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBInstanceClass: !Ref DBInstanceType
      StorageType: !Ref StorageType
      MultiAZ: !Ref MultiAZ
      MasterUsername: !Ref 'DBUser'
      MasterUserPassword: !Ref 'DBPassword'
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      PubliclyAccessible: !Ref PubclicAccess
      DBSnapshotIdentifier: !Ref SnapshotIdent
      DBSubnetGroupName: !Ref DBSubnetGroupName
      BackupRetentionPeriod: 1
      VPCSecurityGroups:
        - !Ref VpcSG
    DeletionPolicy: Delete


